language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
before_install:
  - python --version
  - pip install -U pip
  - pip install poetry
install:
  - poetry install -v
script:
  - pytest